name: Markdown Linting and Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Lint Markdown files
      uses: DavidAnson/markdownlint-cli2-action@v13
      with:
        globs: '**/*.md'
        
    - name: Check for broken links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/link-check-config.json'

  validate-structure:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Validate repository structure
      run: |
        echo "Checking required files and directories..."
        
        # Check for required files
        required_files=(
          "README.md"
          "LICENSE"
          "CONTRIBUTING.md"
          "SECURITY.md"
          ".gitignore"
        )
        
        for file in "${required_files[@]}"; do
          if [[ ! -f "$file" ]]; then
            echo "❌ Missing required file: $file"
            exit 1
          else
            echo "✅ Found: $file"
          fi
        done
        
        # Check for required directories
        required_dirs=(
          "docs"
          "checklists"
          "assets"
          ".github/workflows"
        )
        
        for dir in "${required_dirs[@]}"; do
          if [[ ! -d "$dir" ]]; then
            echo "❌ Missing required directory: $dir"
            exit 1
          else
            echo "✅ Found: $dir"
          fi
        done
        
        echo "Repository structure validation completed successfully!"
